version: "3.6"

services:
  reverse-proxy:
    image: traefik:v2.3
    restart: always
    command:
      - "--log.level=DEBUG"
      - "--api"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=overlay-network-internal"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker.network=web"
      - "--certificatesresolvers.tlsresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.tlsresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.tlsresolver.acme.storage=/letsencrypt/acme.json"

    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - web

networks:
  web: null
  icing: null
